### PR TITLE
Fix: webdriver clean

### PR DESCRIPTION
**Pull request by macroking**
webdriver-manager clean does not remove `chrome.xml`. The metaFiles reference has a different name `chromedriver-response.xml` in the list causing the problem. 
This PR will address that issue.

### CODE REVIEW

**Comment by macroking** [comment]
I signed it!

**Comment by cnishina** [comment]
Please run `npm run format`

**Comment by cnishina** [comment]
other than that, lgtm.

**Comment by cnishina** [comment]
Please rebase. I removed the e2e_spec/desktop_spec.ts

**Comment by macroking** [comment]
rebase done.

**Comment by cnishina** [comment]
This is working now.
https://github.com/angular/webdriver-manager/blob/master/lib/cmds/clean.ts#L34

Each provider has its own clean method. So ChromeDriver calls clean. https://github.com/angular/webdriver-manager/blob/master/lib/provider/chromedriver.ts#L152

And we remove the files based on a regular expression. https://github.com/angular/webdriver-manager/blob/master/lib/provider/utils/file_utils.ts#L230

**Pull request closed without merging**
