### PR TITLE
Shutdown the server cleanly. Fixes #238

### LINKED ISSUE #238: SIGINT causes unhandled error event
# Steps to reproduce

1. Launch webdriver `$ ./bin/webdriver-manager start`
2. Wait for server to come up `... INFO - Selenium Server is up and running`
3. Send `SIGINT` (`⌃c`) to kill server

# Expected behaviour

Process shuts-down server cleanly

# Actual behaviour

Unhandled error is thrown

```
13:30:45.730 INFO - Selenium Server is up and running
^C[13:30:48] I/start - Staying alive until the Selenium Standalone process exits
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketOnEnd (_http_client.js:345:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

This seems to be because Selenium have removed the ability to interact with the driver over http https://github.com/SeleniumHQ/selenium/issues/2958

### PR DESCRIPTION
**Pull request by chrisgedrim**
NOTE: There are no changes to the test suites. Running the tests from angular/webdriver-manager:master resulted in the same errors I was seeing locally

### CODE REVIEW

**Comment by cnishina** [comment]
What is `Error: Cannot find module 'ps-node'`

**Comment by chrisgedrim** [comment]
ps-node is a library for finding processes, I used it to grab the java pid in `shutdown` so I could kill the processs

**Comment by cnishina** [comment]
Please rebase. CircleCI now needs the `npm install` command.

**Comment by cnishina** [comment]
@chrisgedrim  ping for a rebase. Thanks!

**Pull request closed without merging**
