### PR TITLE
fix: crash when assigning value to a property of null/undefined

### PR DESCRIPTION
**Pull request by urrri**
#301

### CODE REVIEW

**Comment by urrri** [comment]
What the heck is this CircleCI does. What is the problem there?

**Comment by cnishina** [comment]
This is a formatting issue. There is a step to clang check the PR. The quick fix is to run `npm run format`, review the diffs, and update your PR.

**Comment by urrri** [comment]
Really!!!!!!!!!!!!!!!!!!!!!
Developers cannot fix STUPID bug in their code during loooong time after bug reports and at least 2 PRs.
And instead of do something you recommend to people that want to help, FORMAT ... code?

What happen with Google?

**Comment by cnishina** [comment]
Apologizes again. I rewrote the entire node module and replaced the master branch. It appears that everything was closed. Anyway, in the new branch we do not use msg and this should not be an issue.

https://github.com/angular/webdriver-manager/blob/master/lib/provider/utils/http_utils.ts#L227

**Pull request closed without merging**
