### PR TITLE
Check seleniumPort when testing selenium

### LINKED ISSUE #212: webdriver-manager start --detach do not detach the server on Windows 8
using `--detach` option with start command do not put the server in background

output of `webdriver-manager start --detach`
```
$ webdriver-manager --detach start
[10:26:28] I/start - java -Dwebdriver.chrome.driver=C:\Users\dnoliver\AppData\Roaming\nvm\v6.7.0\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.27.exe -Dwebdriver.ie.driver=C:\Users\dnoliver\AppData\Roaming\nvm\v6.7.0\node_modules\protractor\node_modules\webdriver-manager\selenium\IEDriverServer3.1.0.exe -Dwebdriver.gecko.driver=C:\Users\dnoliver\AppData\Roaming\nvm\v6.7.0\node_modules\protractor\node_modules\webdriver-manager\selenium\geckodriver-v0.14.0.exe -jar C:\Users\dnoliver\AppData\Roaming\nvm\v6.7.0\node_modules\protractor\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.1.0.jar -port 4444
[10:26:28] I/start - seleniumProcess.pid: 596
10:26:28.356 INFO - Selenium build info: version: '3.1.0', revision: '86a5d70'
10:26:28.357 INFO - Launching a standalone Selenium Server
2017-02-20 10:26:28.375:INFO::main: Logging initialized @293ms
10:26:28.454 INFO - Driver class not found: com.opera.core.systems.OperaDriver
10:26:28.454 INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped:
Unable to create new instances on this machine.
10:26:28.454 INFO - Driver class not found: com.opera.core.systems.OperaDriver
10:26:28.455 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
10:26:28.464 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform WIN8_1
2017-02-20 10:26:28.517:INFO:osjs.Server:main: jetty-9.2.15.v20160210
2017-02-20 10:26:28.556:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@4520ebad{/,null,AVAILABLE}
2017-02-20 10:26:29.072:INFO:osjs.ServerConnector:main: Started ServerConnector@4497bf4c{HTTP/1.1}{0.0.0.0:4444}
2017-02-20 10:26:29.073:INFO:osjs.Server:main: Started @991ms
10:26:29.073 INFO - Selenium Server is up and running
```

System info:

OS: Windows 8
Node Version: v6.7.0
NPM version: v4.2.0
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
webdriver-manager 12.0.2
Working in a network with proxy configuration

### PR DESCRIPTION
**Pull request by bengerman13**
fixes #212

### CODE REVIEW

**Comment by bengerman13** [comment]
I signed the CLA

**Comment by cnishina** [comment]
Seems reasonable.

**Comment by cnishina** [comment]
@bengerman13 What account is "Ben Berry" from the two previous commits? The CLA won't pass if both these accounts do not say yes to the CLA. You could create a new PR with the same commit as the same author and that would be okay too. Anyway, this is LGTM.... just need to satisfy the CLA.

**Comment by bengerman13** [comment]
@cnishina that's me. I had the wrong git config set up. I'll create a new PR

**Comment by bdellegrazie** [comment]
The Circle CI builds look to have failed on API requests to Github ... perhaps rate limiting?

**Comment by cnishina** [comment]
Closing this. I just noticed that there was a previous fix. See https://github.com/angular/webdriver-manager/pull/228

**Pull request closed without merging**
