### PR TITLE
added dev/urandom to selenium start args to prevent startup delays

### PR DESCRIPTION
**Pull request by martin770**

### CODE REVIEW

**Comment by martin770** [comment]
I have signed the CLA, but gitHub is not recognizing me as the author of the commit. Please advise.

**Comment by martin770** [comment]
Thanks Googlebot

**Comment by juliemr** [comment]
LGTM, thanks for digging into this weird stuff.

**Comment by cnishina** [comment]
Split pull request into two commits. Closed with 00740238dc31b71d5dfd0db6c929b47b43c7b0d8 and 18f9f1dfea02cd8f5c5a2cd5f09130f0ca24f68a.

**Pull request closed without merging**
