### PR TITLE
replaced fs.mkdirSync with mkdirp.sync

### PR DESCRIPTION
**Pull request by martin770**
Replaced usages of fs.mkdirSync with mkdirp.sync so that an error will not be thrown if trying to create a directory that already exists.

This is related to the feature request in issue #263.

### CODE REVIEW

**Comment by martin770** [comment]
I fixed the unit tests that were spying on fs.statSync so they wouldn't fail. But there were other unit tests that were intermittently failing (status_spec.js:65, downloader.js:66), and I couldn't figure out why. They didn't seem to have anything to do with my change set.

**Comment by cnishina** [comment]
My guess is that you have created the folder async and are not guaranteed if the folder is there.

**Comment by martin770** [comment]
The same tests are failing for me on master, without my changes. It seems that `status_spec.js` runs into a problem when the beforeEach calls `webdriver-manager update` two times and the `update-config.json` is not written. I don't see any reason why it doesn't write the json file, and no error message about not being able to write it. It's just simply not there in the `selenium_test` directory.

**Comment by cnishina** [comment]
Apologizes for the closed PR. This probably happened when I moved branches?

Anyway, commenting on both the PR and issue.  I swallow mkdirSync errors if the folder exists so this should be fine.

https://github.com/angular/webdriver-manager/blob/master/lib/provider/utils/cloud_storage_xml.ts#L21
https://github.com/angular/webdriver-manager/blob/master/lib/provider/utils/github_json.ts#L32
https://github.com/angular/webdriver-manager/blob/master/lib/provider/utils/file_utils.ts#L141

**Pull request closed without merging**
