### PR TITLE
Support Chrome 76

### PR DESCRIPTION
**Pull request by MathRobin**

### CODE REVIEW

**Comment by MathRobin** [comment]
@googlebot I signed it!

**Comment by MathRobin** [comment]
(please @googlebot : Take careof our privacy please or go fuck yourself, you're the evil.)

**Comment by knagarajan1984** [comment]
Can we have the merge asap please?

**Comment by cnishina** [comment]
lgtm. Sorry for the delay. I'll get this released in the next few minutes.

**Comment by MathRobin** [comment]
Many thanks ! Hope protractor will be updated soon

**Comment by seba161189** [comment]
any news?

**Comment by MathRobin** [comment]
Nope. They said it's already done, but it's not.

**Comment by seba161189** [comment]
i solved with
ng e2e --webdriver-update=false

{
  "name": "ater-2-frontend",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "l": "node script-local && ng serve --o",
    "fase1": "node grab-git-info && node script-fase1 && ng serve --o",
    "fase2": "node grab-git-info && node script-fase2 && ng serve --o",
    "build": "node grab-git-info && ng build",
    "local": "node grab-git-info && node script-local && ng build --base-href=/ater/ --configuration=development",
    "dev": "node grab-git-info && node script-dev && ng build --base-href=/ater/ --configuration=development",
    "uat": "node grab-git-info  && node script-uat && ng build --base-href=/ater/ --configuration=uat",
    "qa": "node grab-git-info  && node script-qa && ng build --base-href=/ater/ --configuration=qa",
    "hexa": "node grab-git-info  && node script-hexa && ng build --base-href=/ater/ --configuration=hexa",
    "prod": "node grab-git-info  && node script-prod && ng build --prod --base-href=/ater/ --configuration=prod",
    "lint": "ng lint",
    "test": "ng test",
    "webdriver-update-ci": "webdriver-manager update --standalone false --gecko false --versions.chrome 2.37",
    "e2e": "ng e2e --webdriver-update=false"
  },
  "private": true,
  "dependencies": {
    "@angular-builders/custom-webpack": "^7.1.1",
    "@angular/animations": "^6.0.0",
    "@angular/cdk": "^6.0.1",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/flex-layout": "^6.0.0-beta.16",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/material": "^6.0.1",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^3.0.1",
    "@types/moment": "^2.13.0",
    "angular2-text-mask": "^9.0.0",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.4",
    "file-saver": "^2.0.2",
    "inputmask": "^4.0.6",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.10",
    "mat-progress-buttons": "^8.0.4",
    "moment": "^2.22.2",
    "ngx-file-drop": "^4.0.6",
    "ngx-mask": "^7.3.6",
    "ngx-mat-select-search": "^1.7.4",
    "ngx-toastr": "^8.6.0",
    "node-sass": "^4.11.0",
    "normalize.css": "^8.0.0",
    "rxjs": "^6.0.0",
    "simple-i18n-text": "^1.0.0",
    "text-mask-addons": "^3.8.0",
    "url-join": "^4.0.0",
    "vanilla-text-mask": "^5.1.1",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.6.3",
    "@angular/cli": "~6.0.0",
    "@angular/compiler-cli": "^6.0.0",
    "@angular/language-service": "^6.0.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/lodash": "^4.14.116",
    "@types/node": "^8.9.5",
    "codelyzer": "~4.2.1",
    "git-describe": "^4.0.3",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.4",
    "phantomjs-prebuilt": "^2.1.16",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2",
    "webpack": "^4.8.3"
  }
}

**Comment by MathRobin** [comment]
Are you sure those flags `--standalone false --gecko false` are necessary ? They don't concern Chrome version update problem ?

**Comment by seba161189** [comment]
im not sure, but its the only way that it works to me

**Comment by benjaminbatista** [comment]
Since this upgrade, I have this issue :
``` session not created: This version of ChromeDriver only supports Chrome version 76 ``` when I'm running my e2e tests. I don't want to update Chrome to version 76. 
Is it possible to use this webdriver-manager version with chrome <76 ? Thank you

**Pull request merged**
