### PR TITLE
fix(update): prompt user to retry when tar.gz downloaded from github.com is corrupt

### PR DESCRIPTION
**Pull request by flyskywhy**
Some time in some place on the earth, the connection with github.com is unstable, thus some times, `webdriver-manager update` will get a corrupt geckodriver-v0.xx.0.tar.gz from github.com and also extract it to a useless geckodriver-v0.xx.0, so if don't workaround by `webdriver-manager start --versions.gecko=v0.EARLY_VERSION.0`, but just `webdriver-manager start`, then selenium-server-standalone will response e.g. such error:
```
[init({"platform":"LINUX","browserName":"firefox"})]
The environment you requested was unavailable.
Unable to create new service: GeckoDriverService
```
This PR prompt user friendly when got a corrupt geckodriver-v0.xx.0.tar.gz

### CODE REVIEW

**Comment by flyskywhy** [comment]
I signed it!

**Comment by cnishina** [comment]
Please run `npm run format` and update this. Thanks.

**Comment by cnishina** [comment]
@flyskywhy please fix formatting. Thanks!

**Comment by cnishina** [comment]
Please rebase.

**Comment by flyskywhy** [comment]
Hi, also rebased with last 2 commit?

**Pull request closed without merging**
