### PR TITLE
docs(versions): add help and version docs

### PR DESCRIPTION
**Pull request by cnishina**

### CODE REVIEW

**Comment by cnishina** [comment]
Documentation has been sparse.

@AndrewFinlay the promised docs.
@jmartine would this documentation have helped?
@kgentes what do you think? You found the super secret menu.

**Comment by jmartine** [comment]
Yes!  This was the information I was looking for.  Thank you.

**Comment by AndrewFinlay** [comment]
It looks great for 12.x but for legacy support it obscures the changes in behaviour of 'update' made at v12.  Specifically that the previous version of update didn't deliver the latest drivers, hence the need for the ability to request specific updates in the first place.  

Only problem is I'm not sure how you'd add it to the docs and if there's enough people that are stuck with node 4 and thus v10 to warrant its inclusion.  Maybe a 'legacy update/support' section for the top level readme, but I'd imagine that anyone who needs to look at the standalone webdriver project when protractor doesn't work due to a driver issue can't be far off turning up the solution in a search anyway.

**Comment by cnishina** [comment]
The good news is that `webdriver-manager update help` has been there since version 10? Anyway, I would happily review a pull request here for legacy support. Moar documentation the better.

**Comment by AndrewFinlay** [comment]
My point really is that pre version 12, update didn't actually update to the latest drivers but gave you the opportunity to download drivers with versions fixed at the time of publishing.  To get the latest drivers you had to discover newer versions of the drivers existed and that they weren't being installed by the update command.  Until you work this out the menu isn't much help because you're blissfully unaware that you even need it.

Hence the request for documenting this particular behaviour, that to get the latest drivers using webdriver < v12 you need to find the version of the driver and specifically instruct webdriver to download it, that you can't rely on webdriver-manager update to do it for you.

**Comment by cnishina** [comment]
Good point...previous to version 12, we had to maintain the version in the `config.json`. Maybe this weekend I'll get aroudn to it. I'll add a new issue.

**Pull request merged**
