### PR TITLE
fix(config): simplify locating configuration file, selenium folder

### PR DESCRIPTION
**Pull request by cnishina**
* Let the bin file decide which webdriver-manager to use
* Use the configuration file / package from the default position
* Selenium folder will always be located to webdriver-manager/selenium/

### CODE REVIEW

**Comment by cletusw** [comment]
@cnishina How do I go about having a project-specific `config.json` file now?

**Comment by cnishina** [comment]
The best option is to start webdriver-manager with project-specific configurations via the CLI.

For example, if the project needs to use ChromeDriver 2.2.0, use the command line option`--versions.chrome=2.20`. To see the entire list of a command like `update`, run `webdriver-manager update help`.

```
❯ webdriver-manager update help

Usage:        update [options]
              update help
Description:  install or update selected binaries

Options:
  --out_dir                   Location to output/expect                               [default: /Users/cnishina/.nvm/versions/node/v6.3.0/lib/node_modules/protractor/node_modules/webdriver-manager/selenium]
  --ignore_ssl                Ignore SSL certificates
  --proxy                     Proxy to use for the install or update command
  --alternate_cdn             Alternate CDN to binaries
  --standalone                Install or update selenium standalone                   [default: true]
  --chrome                    Install or update chromedriver                          [default: true]
  --android                   Update/use the android sdk
  --android-api-levels        Which versions of the android API you want to emulate   [default: 24]
  --android-abis              Which ABIs you want to use in android emulation         [default: x86_64]
  --android-accept-licenses   Automatically accept android licenses
  --ios                       Update the iOS sdk
  --versions.standalone       Optional seleniuim standalone server version            [default: 2.53.1]
  --versions.chrome           Optional chrome driver version                          [default: 2.22]
  --versions.appium           Optional appium version                                 [default: 1.5.3]
  --versions.android          Optional android sdk version                            [default: 24.4.1]
```

**Comment by cletusw** [comment]
Yeah, this is what I'm currently doing, but it also means I lose the
ability to auto-lookup ChromeDriver. I now have to manually set the
`chromeDriver` property in protractor.conf.js as well, which is hacky. If
`webdriver-manager` ever changes it's default output format, I have to
change my string concatenation, even if I'm already using `--out_dir`.

**Comment by cnishina** [comment]
I'm unsure what you mean by "ability to auto-lookup ChromeDriver". And how you are currently using this `chromeDriver` in your protractor.conf.js.

Instead of tagging this onto a submitted PR, please create a new issue. Details for this issue might include:

- What's causing the problem
- Your current work around in protractor.conf.js
- What you wish happened

Thanks!

**Pull request merged**
