### PR TITLE
Documentation for running driver on background

### PR DESCRIPTION
**Pull request by elhigu**
Was implemented here
https://github.com/angular/webdriver-manager/commit/338fffddf68ac2767aa5c226ba5374451b9e5308

### CODE REVIEW

**Comment by elhigu** [comment]
I signed it!

**Comment by cnishina** [comment]
This is a great PR; however, if we are going to document this feature, we should discuss how this works only with the 2.53.x selenium standalone servers and does not currently work for the 3.0.x. See https://github.com/angular/webdriver-manager/issues/199

**Comment by elhigu** [comment]
It is already documented in usage message of the command line client... So should I just add disclaimer to README that shutdown currently works only with 2.53.x server?

I suppose that someone will add support for LifecycleServlet based shutdown for 3.x.x servers at some point.

**Comment by cnishina** [comment]
Yes, let's add a disclaimer that it doesn't work for 3.x.x servers yet. Thanks!

**Pull request merged**
