### PR TITLE
chore: update to latest chrome driver

### PR DESCRIPTION
**Pull request by DevVersion**
* Recently a new version of the chrome-driver has been released (v2.26).
  It includes a lot of fixes for the latest Chrome version.

  https://sites.google.com/a/chromium.org/chromedriver/downloads

FYI: Didn't touch the `browsers.md` in favor of https://github.com/angular/webdriver-manager/pull/174

### CODE REVIEW

**Comment by DevVersion** [comment]
Not sure why the tests failed. My change anything in code formatting 😄

**Comment by cnishina** [comment]
The error is due to a formatting issue. This is not a big deal and should be resolved with one of my PRs.

**Comment by DevVersion** [comment]
Sounds good :+1:

**Comment by cnishina** [comment]
Thanks for looking into this.

**Comment by DevVersion** [comment]
No problem. Thanks for merging. 

What do you think about automatically detecting the chromedriver version?

**Pull request merged**
